feat: update CI/CD pipeline

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -2,7 +2,18 @@ name: CI/CD
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "develop" ]
+
+permissions:
+  id-token: write
+  contents: read
+
+env:
+  AWS_REGION: us-east-2
+  IMAGE_TAG: ${{ github.sha }}
+  ECR_REPOSITORY: speed-violation
+  EC2_INSTANCE_ID: i-0bbd45b10eac2fca4
+  AWS_IAM_ROLE: arn:aws:iam::355103369647:role/github-actions-role
 
 jobs:
   build-and-deploy:
@@ -19,4 +30,49 @@ jobs:
           cache: maven
 
       - name: Run tests
-        run: mvn test     
+        run: mvn test
+
+      - name: Configure AWS credentials (OIDC)
+        uses: aws-actions/configure-aws-credentials@v6
+        with:
+          role-to-assume: ${{ env.AWS_IAM_ROLE }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: ecr-login
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Build and push Docker image
+        env:
+          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+
+      - name: Deploy with SSM
+        run: |
+          COMMAND_ID=$(
+            aws ssm send-command \
+              --instance-ids "$EC2_INSTANCE_ID" \
+              --document-name "AWS-RunShellScript" \
+              --parameters commands="/opt/app/deploy.sh $IMAGE_TAG" \
+              --query "Command.CommandId" --output text
+          )
+          
+          aws ssm wait command-executed \
+            --comand-id "$COMMAND_ID" \
+            --instance-id "$EC2_INSTANCE_ID" \
+            --region "$AWS_REGION" || true
+          
+          STATUS=$(
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "$EC2_INSTANCE_ID" \
+              --region "$AWS_REGION" \
+              --query "Status" --output text
+          )
+          
+          if [ "$STATUS" != "Success" ]; then
+            echo "Deployment failed with status: $STATUS"
+            exit 1
+          fi
